server:
  port: 8816
  servlet:
    context-path: /zyx
spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zyx
    username: root
    password: 123456
  data:
    web:
      pageable:
        default-page-size: 10
        page-parameter: pageNumber
        size-parameter: pageSize
      sort:
        sort-parameter: sort

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.1.91:61616
    pool:
      enabled: true
      max-connections: 10
mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml 
  type-aliases-package: com.zyx.entity


queueName: publish.queue
topicName: publish.topic


